#!/usr/bin/env python3
"""visualize_gamma_corr.py

Reads the CSV generated by gamma_correlation (dataset,gamma,query_id,score,recall)
and calculates Pearson and Spearman correlation between Score (RV) and Recall for
each (dataset, gamma).

Plots Correlation vs Gamma.

Usage:
    EXPERIMENTS_ROOT=/data ./build/gamma_correlation > gamma_corr.csv
    python3 visualize_gamma_corr.py gamma_corr.csv
"""

import sys
import pandas as pd
from scipy.stats import pearsonr, spearmanr
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from pathlib import Path

COLORS = {
    "deep-image-96-angular": "#E63946",
    "glove-100-angular":     "#2A9D8F",
    "sift-128-euclidean":    "#457B9D",
}

DATASET_LABELS = {
    "deep-image-96-angular": "Deep-Image-96",
    "glove-100-angular":     "GloVe-100",
    "sift-128-euclidean":    "SIFT-128",
}

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 visualize_gamma_corr.py <gamma_corr.csv>", file=sys.stderr)
        sys.exit(1)
        
    csv_file = sys.argv[1]
    
    print(f"Reading data from {csv_file}...")
    # Error handling: skip bad lines from stdout leakage
    df = pd.read_csv(csv_file, on_bad_lines='skip')
    
    # Filter only valid dataset rows to discard leaked std::cout prints
    valid_datasets = list(DATASET_LABELS.keys())
    df = df[df['dataset'].isin(valid_datasets)].copy()
    
    # Ensure columns are numeric
    df['gamma'] = pd.to_numeric(df['gamma'], errors='coerce')
    df['score'] = pd.to_numeric(df['score'], errors='coerce')
    df['recall'] = pd.to_numeric(df['recall'], errors='coerce')
    df = df.dropna(subset=['gamma', 'score', 'recall'])
    
    results = []
    
    print("\nCalculating correlations...")
    # Group by dataset and gamma
    for (ds, gamma), group in df.groupby(['dataset', 'gamma']):
        scores = group['score'].values
        recalls = group['recall'].values
        
        # Check if variance is zero (all recalls or scores are identical)
        if scores.std() == 0 or recalls.std() == 0:
            pearson = 0.0
            spearman = 0.0
        else:
            pearson, _ = pearsonr(scores, recalls)
            spearman, _ = spearmanr(scores, recalls)
            
        results.append({
            'dataset': ds,
            'gamma': float(gamma),
            'pearson': pearson,
            'spearman': spearman
        })
        
    res_df = pd.DataFrame(results)
    
    # Print Summary Table
    print("\n─── Summary: Score (RV) to Recall Correlation ─────────────")
    print(f"{'Dataset':<25} {'γ':>6} {'Pearson':>10} {'Spearman':>10}")
    print("─" * 55)
    for ds in sorted(res_df['dataset'].unique()):
        ds_data = res_df[res_df['dataset'] == ds].sort_values('gamma')
        for _, row in ds_data.iterrows():
            marker = " ←" if row['gamma'] == 16.0 else ""
            print(f"{row['dataset']:<25} {row['gamma']:>6.1f} {row['pearson']:>10.4f} {row['spearman']:>10.4f}{marker}")
    print("─" * 55)

    # Plot
    datasets = sorted(res_df['dataset'].unique())
    n = len(datasets)
    
    fig, axes = plt.subplots(1, n, figsize=(5 * n, 4), squeeze=False)
    fig.suptitle("Correlation between Score (RV) and Actual Recall vs Gamma", fontsize=14, y=1.05)
    
    default_gamma = 16.0
    
    for col, ds in enumerate(datasets):
        ax = axes[0, col]
        ds_data = res_df[res_df['dataset'] == ds].sort_values('gamma')
        
        gammas = ds_data['gamma'].values
        pearsons = ds_data['pearson'].values
        spearmans = ds_data['spearman'].values
        
        color = COLORS.get(ds, "#666666")
        label = DATASET_LABELS.get(ds, ds)
        
        ax.plot(gammas, pearsons, marker='o', linewidth=2, color=color, label='Pearson')
        ax.plot(gammas, spearmans, marker='s', linestyle='--', linewidth=1.5, color=color, alpha=0.8, label='Spearman')
        
        if default_gamma in gammas:
            idx = list(gammas).index(default_gamma)
            ax.axvline(x=default_gamma, color='gray', linestyle=':', linewidth=1)
            ax.scatter([default_gamma]*2, [pearsons[idx], spearmans[idx]], 
                       s=100, zorder=5, color=color, edgecolors='black')
                       
        ax.set_title(label, fontsize=12, fontweight='bold')
        ax.set_xlabel("γ (gamma)", fontsize=11)
        ax.set_ylabel("Correlation Coefficient", fontsize=11)
        ax.set_xscale("log", base=2)
        ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f"{x:g}"))
        ax.grid(True, linestyle="--", alpha=0.4)
        ax.legend(fontsize=9, loc='best')
        ax.set_ylim(0.0, 1.0)
        
    plt.tight_layout()
    out_path = Path(__file__).parent / "gamma_corr_plot.png"
    fig.savefig(out_path, dpi=150, bbox_inches='tight')
    print(f"\nPlot saved to: {out_path}")

if __name__ == "__main__":
    main()
