#!/usr/bin/env python3
"""visualize_ablation.py

Parses logs generated by:
  - ablation_study_weighted_decay_function() (Gamma sweep)
  - ablation_study_truncation_ratio() (Alpha sweep)
  
Extracts the results and plots Avg/p5/p1 Recall, Median Search Time, and WAE
across the swept parameter for each dataset.

Usage:
    ./build/run > ablation.log
    python3 visualize_ablation.py ablation.log
"""

import sys
import re
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import collections
from pathlib import Path

# ── Data Structures ────────────────────────────────────────────────────────────
AblationRecord = collections.namedtuple("AblationRecord", [
    "dataset", "param_val", "wae", "median_time", "avg_recall", "p5_recall", "p1_recall"
])

DATASET_LABELS = {
    "deep-image-96-angular": "Deep-Image-96",
    "glove-100-angular":     "GloVe-100",
    "sift-128-euclidean":    "SIFT-128",
}

COLORS = {
    "deep-image-96-angular": "#E63946",
    "glove-100-angular":     "#2A9D8F",
    "sift-128-euclidean":    "#457B9D",
}

# ── Parser ─────────────────────────────────────────────────────────────────────
def parse_log(filepath):
    gamma_data = collections.defaultdict(list)
    alpha_data = collections.defaultdict(list)
    
    curr_dataset = None
    curr_param_type = None  # 'gamma' or 'alpha'
    curr_param_val = None
    curr_wae = None
    
    re_dataset = re.compile(r"^Dataset:\s+(\S+)")
    re_gamma   = re.compile(r"^---\s+Gamma:\s+([0-9.eE+\-]+)\s+---")
    re_alpha   = re.compile(r"^---\s+Alpha:\s+([0-9.eE+\-]+)\s+---")
    re_wae     = re.compile(r"^\*\*\*\*Weighted average ef:\s+(\d+)")
    
    # Matches the 8-value CSV line output by adaptive_search
    # e.g., "1025, 8449, 0.9762, 0.92, 0.88, 100, 150, 200"
    re_results = re.compile(r"^\s*\d+\s*,\s*(\d+)\s*,\s*([0-9.]+)\s*,\s*([0-9.]+)\s*,\s*([0-9.]+)\s*,")

    with open(filepath, "r") as f:
        for line in f:
            line = line.strip()
            
            m = re_dataset.search(line)
            if m:
                curr_dataset = m.group(1)
                continue
                
            m = re_gamma.search(line)
            if m:
                curr_param_type = 'gamma'
                curr_param_val = float(m.group(1))
                continue
                
            m = re_alpha.search(line)
            if m:
                curr_param_type = 'alpha'
                curr_param_val = float(m.group(1))
                continue
                
            m = re_wae.search(line)
            if m:
                curr_wae = int(m.group(1))
                continue
                
            m = re_results.search(line)
            if m and curr_dataset and curr_param_type and curr_param_val is not None:
                median_time = int(m.group(1))
                avg_recall  = float(m.group(2))
                p5_recall   = float(m.group(3))
                p1_recall   = float(m.group(4))
                
                rec = AblationRecord(
                    dataset=curr_dataset,
                    param_val=curr_param_val,
                    wae=curr_wae if curr_wae is not None else 0,
                    median_time=median_time,
                    avg_recall=avg_recall,
                    p5_recall=p5_recall,
                    p1_recall=p1_recall
                )
                
                if curr_param_type == 'gamma':
                    gamma_data[curr_dataset].append(rec)
                else:
                    alpha_data[curr_dataset].append(rec)
                    
                # reset
                curr_wae = None

    return gamma_data, alpha_data

# ── Plotting ───────────────────────────────────────────────────────────────────
def plot_ablation(data_dict, param_name, out_filename):
    datasets = sorted(data_dict.keys())
    if not datasets:
        return
        
    n = len(datasets)
    ROWS = 3
    fig, axes = plt.subplots(ROWS, n, figsize=(6 * n, 4 * ROWS), squeeze=False)
    
    title = f"{param_name.capitalize()} Ablation Study"
    fig.suptitle(title, fontsize=16, y=1.02, fontweight='bold')
    
    row_titles = ["Recall Metrics", "Median Search Time (ms)", "Weighted Avg EF (WAE)"]
    
    # Sort each dataset's records by the parameter value
    for ds in datasets:
        data_dict[ds].sort(key=lambda x: x.param_val)

    # Hardcoded defaults to highlight if present
    default_val = 16.0 if param_name == 'gamma' else 0.25
    
    for col, ds in enumerate(datasets):
        rows = data_dict[ds]
        x_vals  = [r.param_val   for r in rows]
        rec_avg = [r.avg_recall  for r in rows]
        rec_p5  = [r.p5_recall   for r in rows]
        rec_p1  = [r.p1_recall   for r in rows]
        times   = [r.median_time for r in rows]
        waes    = [r.wae         for r in rows]
        
        y_series = [
            (rec_avg, rec_p5, rec_p1),  # Row 0 gets all 3 recall lines
            (times,),                   # Row 1 gets time
            (waes,)                     # Row 2 gets WAE
        ]
        
        color = COLORS.get(ds, "#666666")
        label = DATASET_LABELS.get(ds, ds)
        
        for row_idx, (ax, series_tuple, rtitle) in enumerate(zip(axes[:, col], y_series, row_titles)):
            
            if row_idx == 0:
                ax.plot(x_vals, series_tuple[0], marker="o", lw=2, color=color, label="Avg Recall")
                ax.plot(x_vals, series_tuple[1], marker="s", lw=1.5, ls="--", color=color, alpha=0.8, label="5th %ile")
                ax.plot(x_vals, series_tuple[2], marker="^", lw=1.5, ls=":", color=color, alpha=0.6, label="1st %ile")
            else:
                ax.plot(x_vals, series_tuple[0], marker="o", lw=2, color=color, label=label)
            
            # Highlight default
            if default_val in x_vals:
                idx = x_vals.index(default_val)
                ax.axvline(x=default_val, color="gray", linestyle="--", linewidth=1, alpha=0.7)
                if row_idx == 0:
                    ax.scatter([default_val]*3, [series_tuple[0][idx], series_tuple[1][idx], series_tuple[2][idx]],
                               s=80, zorder=5, color=color, edgecolors="black", linewidths=1.2)
                else:
                    ax.scatter([default_val], [series_tuple[0][idx]],
                               s=100, zorder=5, color=color, edgecolors="black", linewidths=1.5)

            # Labels and scales
            ax.set_xlabel(f"{param_name.capitalize()} Value", fontsize=11)
            ax.set_ylabel(rtitle, fontsize=11)
            
            # Use log2 scale for gamma, linear for alpha
            if param_name == 'gamma':
                ax.set_xscale("log", base=2)
                
            ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f"{x:g}"))
            ax.tick_params(axis="both", labelsize=9)
            ax.grid(True, which="both", linestyle="--", alpha=0.4)
            
            if row_idx == 0:
                ax.set_title(label, fontsize=13, fontweight="bold")
                ax.axhline(y=0.95, color="orange", linestyle="-.", linewidth=1.5, label="Target (0.95)")
                min_y = min(min(rec_p1), min(rec_p5), min(rec_avg))
                max_y = max(max(rec_p1), max(rec_p5), max(rec_avg))
                ax.set_ylim(max(0, min_y - 0.02), min(1.01, max_y + 0.02))
                
            ax.legend(fontsize=8, loc="best")
            
    plt.tight_layout()
    out_path = Path(__file__).parent / out_filename
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    print(f"Saved {param_name} ablation plot to: {out_path}")

def print_summary(data_dict, param_name):
    if not data_dict:
        return
    print(f"\n─── {param_name.capitalize()} Ablation Summary ───────────────────────────────────────────────")
    print(f"{'Dataset':<25} {param_name:>6} {'Avg Rec':>10} {'p5 Rec':>10} {'p1 Rec':>10} {'Time(ms)':>9} {'WAE':>5}")
    print("─" * 83)
    for ds in sorted(data_dict.keys()):
        for r in sorted(data_dict[ds], key=lambda x: x.param_val):
            default_val = 16.0 if param_name == 'gamma' else 0.25
            marker = " ←" if r.param_val == default_val else ""
            print(f"{ds:<25} {r.param_val:>6.2f} {r.avg_recall:>10.4f} {r.p5_recall:>10.4f} {r.p1_recall:>10.4f} "
                  f"{r.median_time:>9} {r.wae:>5}{marker}")
    print("─" * 83)

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 visualize_ablation.py <ablation.log>", file=sys.stderr)
        sys.exit(1)
        
    log_path = sys.argv[1]
    print(f"Parsing {log_path}...")
    
    gamma_data, alpha_data = parse_log(log_path)
    
    if not gamma_data and not alpha_data:
        print("No valid ablation data found in log file.")
        sys.exit(1)
        
    if gamma_data:
        print_summary(gamma_data, 'gamma')
        plot_ablation(gamma_data, 'gamma', 'ablation_gamma_plot.png')
        
    if alpha_data:
        print_summary(alpha_data, 'alpha')
        plot_ablation(alpha_data, 'alpha', 'ablation_alpha_plot.png')

if __name__ == "__main__":
    main()
